version: '3.8'

services:
  web:
    build: .
    depends_on:
      - db
    networks:
      - default
    ports:
      - 8000:5000
    restart: always
    volumes:
      - ./app:/justbegin/app
  db:
    image: postgres:latest
    container_name: db
    environment:
        # - POSTGRES_USER=xh4vm
        - POSTGRES_PASSWORD=xh4vm
        # - POSTGRES_DB=justbegin
    networks:
      - default
    ports:
      - 5432:5432
    restart: unless-stopped
    volumes:
      - ./postgres-data:/var/lib/postgresql/data