version: '3.8'

services:
  frontend:
    build: ./frontend
    container_name: frontend_conteiner
    command: npm run start
    ports:
      - "3000:3000"
    restart: unless-stopped
    stdin_open: true
    tty: true
    volumes:
      - ./frontend/src:/usr/src/app/src
  web:
    build: .
    environment:
        STAGE: test
        SQLALCHEMY_DATABASE_URI: postgresql+psycopg2://test:test@db/test
    depends_on:
      - db
    networks:
      - default
    ports:
      - 8000:5000
    restart: always
    volumes:
      - ./app:/justbegin/app
      - ./tests:/justbegin/tests
  db:
    image: postgres:latest
    container_name: db
    environment:
        POSTGRES_USER: test
        POSTGRES_PASSWORD: test
        POSTGRES_DB: test
    networks:
      - default
    ports:
      - 5432:5432
    restart: unless-stopped
    volumes:
      - ./postgres-data:/var/lib/postgresql/data