version: '3.8'

services:
  web:
    build: .
    depends_on:
      - db
    networks:
      - default
    ports:
      - 8000:5000
    restart: always

  db:
    image: postgres:latest
    environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
        POSTGRES_DB: justbegin
    networks:
      - default
    ports:
      - 5432:5432
    restart: always
    volumes:
      - ./postgres-data:/var/lib/postgresql/data